### ISSUE TITLE
Power Ups timer continuing whilst paused

### ISSUE THREAD

**Issue by roh518** [dislocated-su/ENG1-2#74]
Currently the implementation of Power Ups means that the duration of the effect continues whilst the game is paused, until we implement such a feature (such as for saving and such things), implementing this will be difficult, so I have created this issue to mark it.

**Comment by dislocated-su** [comment]
But we don't have a pause feature? Or do you mean it will be incompatible with a future one?

**Comment by dislocated-su** [comment]
I've made an issue relating to the pause screen now: #92
